[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/_next/image/*"
  query = { q = ":quality", url = ":url", w = ":width" }
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/_next/image/*"

  [headers.values]
    Strict-Transport-Security = "max-age=31536000"
    X-Test = 'foobar'

[[plugins]]
  package = "@netlify/plugin-nextjs"
